language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "Bjc0jQlwoFJ0vgyekXcXFTCP0MQA5xEkm4abow2FIW7hgcXR5C9/6EUMW0HSLAU3+CU+06ByiXcY8BwcvKd0HiZYpRUmsjOXFRXKlRf9VUU6HJj88EzAICaynfWvULGsXCAf1EABSNvwgmYwKtX+DL4BnJtMgEpUKA9/6tfsFz0z9lIleUc0gCz+bSn1PM17HmFaVi05M2+A6mY0nIR7l3Cd3jgm1Q6LaN9mElUfq/qjqwb4YMYlo9yuALMbJ1dV2N0hHpWJbW5PraK/oV2+G8zpNgn0U+V279+9UdmbuUNbtY+Q4nHclpE6XMy4PJGnYISaS1MbdfZzW6d0UoSW45vZuzRKbRMXEve3RmDyaLI6Dc+T5n6xyduvpRX9Tgxno6kpSecZy/jiFyCiIq5NVUGmktOPBKDzIbvP04WOw/6koivL0Zip8hyqbC+CGnfevxZXBNhozRJEFyZFVk2Kb7CgkhJwIbcjq5Q6zljb03SJVTd8UE4JxcYmB2pYvjzWPowvT1NhrENJ6gdArol66Ifkfj5dGUcMegX+6HlAISyewiH9UjhQuBZt19XAsnLIdU6iYglvfZAZKbkrUsK5cVzBJiWFTiGH+LZOBonggRke7lTwsg9EFl4/oUB6CTp0Yg9JBVKwvQqpNbvbWHGSs2mtSLuAXcVs+OGgRBRSi6A="
  - secure: "R3Kb8vTMYosrPiDT7TSp2Lw5aCZKRK43PbBbni1bJ0xiYsPHDltrSMwanJcXCrZojQ+1SzTD+wb509o3/hBS91wJLM/OYTHFLNtGv4e4ULVNBWWoJzEJOQH8X51KeWBBtd0CXw/1A9P5WcJt8NXSHysRWTXEQrXr1ItYHbbMZtBG4S0XtQ4hgvNsLqw7/iEkCsZZeCINxiQ3Fus4eAIalXIQmNx3dfxNyVdAtmYgyUOfbLbYTLFluZp6c4kvIPggrg1aM4hZmlqGn60Po7LgynpiivG9TRSGSLIKC3hzY7p0EfNABbwvIKG14gACCT1DIzsF/6/W1sAPhZn8CoawK6df7kdJyltQv62KRKDVdwW8zRAM9Q8o04MIAB2pgLUjH0fvwMlP2F8FI4DQ9ca0LS2ibDnbxDojKAoxNiV3ioxZdEUOi3GE/TYv2hjueSyJsji7Ws6u11orhFivlXDEfD0D247zsUj9Lp/0/UD3vtr/cc3Pi295qwxSBBENkfdZFQUrJ7S37xOkpm/ygzR+O2Fam5a9sgMDky9I/qEJZWccXhN10grcQkjEq8j9SA3BssCn5jeKEQjWNnfqJdaTpUmMpNCJE8f/iSYnikLzuhd7fnne83+ZnvK72mX9yK3g7cD0Opytaq4J9XCs8/RWOnao4OoRcjLvQZ5Lsvvuxfg="
deploy:
  provider: releases
  api_key: 
    secure: "fwGJAOo+39DNQ059KQ8jwZeXgZ6EICSwRdtewvyEv9e8i6GKotSDYZ1NBS5X88Vsn/s5/mKMNnd5CQ0ezRSHOYgUx35oDlbqgIFqVkFc7mPDFYENw3BdU2dkEN9QtOrLDw+ojZKhq6zOLEcGIGLiM75woI1TmziKELO2u9/zsagbx++T1hmzte4CwXjGTStulWcW8unxibrS4nLysGrv4SIo69KzeV6luHo6TMRA/FyAiXt0bms/5sFzmKcAWr7ea0jBp7NUlsnRC5+zbXYNRGWdVgAAYB+CpaeO4Kb5l2j/cIVW/9BqnLZ5Iae32oXRDOs2RX5Kghj/pUv5Ot61JyH4qKbGWgtci5nCpXBP+4pLKlv6Ad5LGFXU6/YOpDct1vhVac01VMqOibuMq8N3Se4FeqANrTDA9gIF4IAyMrNCbY9SUvIQF/AhMr3N6U3W49pdN7XmscHh2dGtrNpTLpUC9Azx3yRoN4oPa6Gnzq6EuL9wJ6slOJ+gLG4dHpomLwJIXDwlFvMEyTm2UfQTajR9Qcn/h5DrSKlMM9dznyVZ3XuENEsbYBvI5kgaZ9TzbVC3t/8mgyeWFsjx10LHRrgl2EjsMk6996bagLTMkOwkesrsSgU/IGU7KhSEJXFGS5GnEu9hqEaCTYMeZIT8cbp9X/MBAbo2DQeeGrOue4s="
  file_glob: true
  file: 
    - "Plugin/target/PacketListenerAPI_v*.jar"
  skip_cleanup: true
  on:
    tags: true
